// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD57gbDafbIf3FCPTj44yEQ1LI5VtUZCB4',
    appId: '1:178430968967:web:c91e6480d27e2867196422',
    messagingSenderId: '178430968967',
    projectId: 'judgeappfinal',
    authDomain: 'judgeappfinal.firebaseapp.com',
    storageBucket: 'judgeappfinal.firebasestorage.app',
    measurementId: 'G-D8YRXF4329',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtcIOuOdr8SZ7-4aP-91ehu3to_THFGDE',
    appId: '1:178430968967:android:8a173cf47019ef79196422',
    messagingSenderId: '178430968967',
    projectId: 'judgeappfinal',
    storageBucket: 'judgeappfinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYAb6QG8sojfh0wH0LdeuoPNz6j4kKJZ0',
    appId: '1:178430968967:ios:93e8c1832c7a2ee0196422',
    messagingSenderId: '178430968967',
    projectId: 'judgeappfinal',
    storageBucket: 'judgeappfinal.firebasestorage.app',
    iosBundleId: 'com.example.judgeappfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYAb6QG8sojfh0wH0LdeuoPNz6j4kKJZ0',
    appId: '1:178430968967:ios:93e8c1832c7a2ee0196422',
    messagingSenderId: '178430968967',
    projectId: 'judgeappfinal',
    storageBucket: 'judgeappfinal.firebasestorage.app',
    iosBundleId: 'com.example.judgeappfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD57gbDafbIf3FCPTj44yEQ1LI5VtUZCB4',
    appId: '1:178430968967:web:8d7f6fcb31036949196422',
    messagingSenderId: '178430968967',
    projectId: 'judgeappfinal',
    authDomain: 'judgeappfinal.firebaseapp.com',
    storageBucket: 'judgeappfinal.firebasestorage.app',
    measurementId: 'G-LGN26YCGRT',
  );
}
